from __future__ import annotations

import html
import re
import ssl
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import datetime, time, timedelta
from typing import Any
from zoneinfo import ZoneInfo

from .settings import MOSCOW_TZ


LIST_URL = "https://m.dme.ru/Ru/autogenerated/Flight/OnlineTableFlightList"
DETAIL_URL = "https://m.dme.ru/Ru/autogenerated/Flight/DetailedFlight"
REFERER = "https://m.dme.ru/passengers/flight/live-board/?column=4&sort=1&direction=D&page=1"


@dataclass(frozen=True)
class DmeRow:
    flight_code: str
    planned_time: str
    detail_id: str


def enrich_dme_gates(flights: list[dict[str, Any]]) -> dict[str, Any]:
    now = datetime.now(ZoneInfo(MOSCOW_TZ))
    missing_keys = {
        _flight_key(flight)
        for flight in flights
        if _flight_key(flight) and not _known_gate(flight)
    }
    if not missing_keys:
        return {"dme_official_checked": 0, "dme_official_filled": 0}

    rows = _fetch_rows(now)
    checked = 0
    gates: dict[str, str] = {}
    for row in rows:
        key = f"{_normalize_code(row.flight_code)}|{row.planned_time}"
        if key not in missing_keys or not _is_near_now(row.planned_time, now):
            continue
        checked += 1
        gate = _fetch_gate(row.detail_id)
        if gate:
            gates[key] = gate

    filled = 0
    for flight in flights:
        key = _flight_key(flight)
        gate = gates.get(key)
        if not gate:
            continue
        departure = flight.setdefault("departure", {})
        departure["gate"] = gate
        if not departure.get("terminal"):
            departure["terminal"] = "T1"
        departure["gateSource"] = "официальный DME"
        departure["gateMatch"] = "рейс + время"
        flight["secondaryCorner"] = f"Gate {gate}"
        filled += 1

    return {"dme_official_checked": checked, "dme_official_filled": filled}


def _fetch_rows(now: datetime) -> list[DmeRow]:
    result: list[DmeRow] = []
    seen_ids: set[str] = set()
    curr_date = now.date().isoformat()

    for page in range(4):
        body = urllib.parse.urlencode(
            {
                "CurrDateStr": curr_date,
                "SearchText": "",
                "direction": "D",
                "PeriodDay": "0",
                "Page": str(page),
            }
        ).encode("utf-8")
        text = _request_text(
            LIST_URL,
            data=body,
            headers={
                "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                "X-Requested-With": "XMLHttpRequest",
                "Referer": REFERER,
            },
        )
        page_rows = _parse_rows(text)
        page_rows = [row for row in page_rows if row.detail_id not in seen_ids]
        if not page_rows:
            break
        for row in page_rows:
            seen_ids.add(row.detail_id)
        result.extend(page_rows)

    return result


def _parse_rows(text: str) -> list[DmeRow]:
    rows: list[DmeRow] = []
    for block in re.findall(r"<li\b.*?</li>", text, re.S | re.I):
        detail_match = re.search(r"DetailedFlight\?id=(\d+)", block)
        time_match = re.search(r"plannedDateFlight[^>]*>\s*([^<]+)", block, re.S | re.I)
        flight_match = re.search(r"flightNumber.*?<div[^>]*>\s*(.*?)\s*</div>", block, re.S | re.I)
        if not detail_match or not time_match or not flight_match:
            continue
        flight_text = _plain(flight_match.group(1))
        code_match = re.search(r"\b([A-ZА-Я0-9]{1,3})\s*0*([0-9]{1,4}[A-ZА-Я]?)\b", flight_text, re.I)
        time_text = _plain(time_match.group(1))
        if not code_match or not re.match(r"^\d{1,2}:\d{2}$", time_text):
            continue
        rows.append(DmeRow(flight_code=f"{code_match.group(1)} {code_match.group(2)}", planned_time=time_text, detail_id=detail_match.group(1)))
    return rows


def _fetch_gate(detail_id: str) -> str:
    url = f"{DETAIL_URL}?id={urllib.parse.quote(detail_id)}"
    text = _request_text(url, headers={"Referer": REFERER})
    plain = _plain(text)
    match = re.search(r"\bГейт\s+([A-ZА-Я]?\d+[A-ZА-Я]?)\b", plain, re.I)
    return match.group(1).upper() if match else ""


def _request_text(url: str, data: bytes | None = None, headers: dict[str, str] | None = None) -> str:
    request_headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
        "Accept-Language": "ru-RU,ru;q=0.9,en;q=0.8",
    }
    if headers:
        request_headers.update(headers)
    request = urllib.request.Request(url, data=data, headers=request_headers, method="POST" if data else "GET")
    with urllib.request.urlopen(request, timeout=45, context=ssl.create_default_context()) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def _flight_key(flight: dict[str, Any]) -> str:
    airline = flight.get("airline") or {}
    code = _normalize_code(f"{airline.get('iata', '')} {flight.get('flightNumber', '')}")
    planned_time = _time_text((flight.get("originalTime") or {}).get("text"))
    return f"{code}|{planned_time}" if code and planned_time else ""


def _normalize_code(value: str) -> str:
    return re.sub(r"[^A-Za-zА-Яа-я0-9]", "", value or "").upper()


def _known_gate(flight: dict[str, Any]) -> bool:
    departure = flight.get("departure") or {}
    gate = str(departure.get("gate") or "").strip()
    return bool(gate and gate.lower() not in {"не указан", "n/a", "--", "$undefined"})


def _is_near_now(value: str, now: datetime) -> bool:
    parsed = _parse_hhmm(value)
    if not parsed:
        return False
    flight_dt = datetime.combine(now.date(), parsed, tzinfo=now.tzinfo)
    return now - timedelta(hours=3) <= flight_dt <= now + timedelta(hours=3)


def _parse_hhmm(value: str) -> time | None:
    match = re.match(r"^(\d{1,2}):(\d{2})$", value or "")
    if not match:
        return None
    hour = int(match.group(1))
    minute = int(match.group(2))
    if hour > 23 or minute > 59:
        return None
    return time(hour, minute)


def _time_text(value: str) -> str:
    match = re.search(r"\d{1,2}:\d{2}", value or "")
    return match.group(0) if match else ""


def _plain(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", value or ""))).replace("\xa0", " ").strip()
