from __future__ import annotations

import html
import re
import ssl
import time as time_lib
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import datetime, time, timedelta
from typing import Any
from zoneinfo import ZoneInfo

from .settings import MOSCOW_TZ


LIST_URL = "https://m.dme.ru/Ru/autogenerated/Flight/OnlineTableFlightList"
DETAIL_URL = "https://m.dme.ru/Ru/autogenerated/Flight/DetailedFlight"
REFERER = "https://m.dme.ru/passengers/flight/live-board/?column=4&sort=1&direction=D&page=1"
DME_GATE_LOOKBACK = timedelta(minutes=90)
DME_GATE_LOOKAHEAD = timedelta(minutes=150)
MAX_DETAIL_CHECKS_PER_RUN = 35
DETAIL_REQUEST_PAUSE_SECONDS = 0.2
DME_DETAIL_ATTEMPTS = 2
DME_DETAIL_RETRY_PAUSE_SECONDS = 2.0


@dataclass(frozen=True)
class DmeRow:
    flight_code: str
    planned_time: str
    detail_id: str


def enrich_dme_gates(flights: list[dict[str, Any]]) -> dict[str, Any]:
    now = datetime.now(ZoneInfo(MOSCOW_TZ))
    missing_flights = [flight for flight in flights if not _known_gate(flight)]
    missing_keys = {
        key
        for flight in missing_flights
        for key in _flight_keys(flight)
    }
    if not missing_keys:
        return {
            "dme_missing_before": 0,
            "dme_official_checked": 0,
            "dme_official_filled": 0,
            "dme_official_skipped": "все видимые рейсы уже с gate",
        }

    try:
        rows = _fetch_rows(now)
    except Exception as exc:
        return {
            "dme_missing_before": len(missing_flights),
            "dme_official_checked": 0,
            "dme_official_filled": 0,
            "dme_official_error": str(exc),
        }

    checked = 0
    detail_errors: list[str] = []
    gates: dict[str, str] = {}
    for row in rows:
        key = f"{_normalize_code(row.flight_code)}|{row.planned_time}"
        if not _is_near_now(row.planned_time, now):
            continue
        if checked >= MAX_DETAIL_CHECKS_PER_RUN:
            break
        checked += 1
        try:
            gate = _fetch_gate_with_retries(row.detail_id)
        except Exception as exc:
            detail_errors.append(f"{row.flight_code} {row.planned_time}: {exc}")
            continue
        if gate:
            gates[key] = gate
        time_lib.sleep(DETAIL_REQUEST_PAUSE_SECONDS)

    existing_keys = {
        key
        for flight in flights
        for key in _flight_keys(flight)
    }

    filled = 0
    for flight in flights:
        gate = next((gates[key] for key in _flight_keys(flight) if key in gates), "")
        if not gate:
            continue
        departure = flight.setdefault("departure", {})
        departure["gate"] = gate
        if not departure.get("terminal"):
            departure["terminal"] = "T1"
        departure["gateSource"] = "официальный DME"
        departure["gateMatch"] = "рейс + время"
        flight["secondaryCorner"] = f"Gate {gate}"
        filled += 1

    added = 0
    for row in rows:
        key = f"{_normalize_code(row.flight_code)}|{row.planned_time}"
        gate = gates.get(key)
        if not gate or key in existing_keys:
            continue
        airline_iata, flight_number = _split_flight_code(row.flight_code)
        if not airline_iata or not flight_number:
            continue
        flights.append(
            {
                "id": f"DME-official-{_normalize_code(row.flight_code)}-{row.planned_time}",
                "airline": {"iata": airline_iata, "name": ""},
                "flightNumber": flight_number,
                "city": "",
                "arrival": {"iata": "", "flag": "", "countryCode": ""},
                "departure": {
                    "iata": "DME",
                    "terminal": "T1",
                    "gate": gate,
                    "gateSource": "official DME live board",
                    "gateMatch": "official DME: flight + time",
                },
                "dataQuality": "gate from official DME live board; direction is filled from post-fact source",
                "destinationSource": "",
                "originalTime": {"text": row.planned_time},
                "newTime": {"text": ""},
                "secondaryCorner": f"Gate {gate}",
                "status": [{"type": "text", "text": "Scheduled"}],
            }
        )
        existing_keys.add(key)
        added += 1

    return {
        "dme_missing_before": len(missing_flights),
        "dme_missing_after": max(len(missing_flights) - filled, 0),
        "dme_official_rows": len(rows),
        "dme_official_checked": checked,
        "dme_official_check_window_minutes": f"-{int(DME_GATE_LOOKBACK.total_seconds() // 60)}..+{int(DME_GATE_LOOKAHEAD.total_seconds() // 60)}",
        "dme_official_filled": filled,
        "dme_official_added_gate_candidates": added,
        "dme_official_detail_errors": detail_errors[:3],
    }


def _fetch_rows(now: datetime) -> list[DmeRow]:
    result: list[DmeRow] = []
    seen_ids: set[str] = set()
    curr_date = now.date().isoformat()

    for page in range(4):
        body = urllib.parse.urlencode(
            {
                "CurrDateStr": curr_date,
                "SearchText": "",
                "direction": "D",
                "PeriodDay": "0",
                "Page": str(page),
            }
        ).encode("utf-8")
        text = _request_text(
            LIST_URL,
            data=body,
            headers={
                "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                "X-Requested-With": "XMLHttpRequest",
                "Referer": REFERER,
            },
        )
        page_rows = _parse_rows(text)
        page_rows = [row for row in page_rows if row.detail_id not in seen_ids]
        if not page_rows:
            break
        for row in page_rows:
            seen_ids.add(row.detail_id)
        result.extend(page_rows)

    return result


def _parse_rows(text: str) -> list[DmeRow]:
    rows: list[DmeRow] = []
    for block in re.findall(r"<li\b.*?</li>", text, re.S | re.I):
        detail_match = re.search(r"DetailedFlight\?id=(\d+)", block)
        time_match = re.search(r"plannedDateFlight[^>]*>\s*([^<]+)", block, re.S | re.I)
        flight_match = re.search(r"flightNumber.*?<div[^>]*>\s*(.*?)\s*</div>", block, re.S | re.I)
        if not detail_match or not time_match or not flight_match:
            continue
        flight_text = _plain(flight_match.group(1))
        code_match = re.search(r"\b([A-ZА-Я0-9]{1,3})\s*0*([0-9]{1,4}[A-ZА-Я]?)\b", flight_text, re.I)
        time_text = _plain(time_match.group(1))
        if not code_match or not re.match(r"^\d{1,2}:\d{2}$", time_text):
            continue
        rows.append(DmeRow(flight_code=f"{code_match.group(1)} {code_match.group(2)}", planned_time=time_text, detail_id=detail_match.group(1)))
    return rows


def _fetch_gate(detail_id: str) -> str:
    url = f"{DETAIL_URL}?id={urllib.parse.quote(detail_id)}"
    text = _request_text(url, headers={"Referer": REFERER})
    plain = _plain(text)
    patterns = (
        r"\b(?:Гейт|Gate)\s*[:№]?\s*([A-ZА-Я]?\d+[A-ZА-Я]?)\b",
        r"\b(?:Выход на посадку|Boarding gate)\s*[:№]?\s*([A-ZА-Я]?\d+[A-ZА-Я]?)\b",
    )
    for pattern in patterns:
        match = re.search(pattern, plain, re.I)
        if match:
            return match.group(1).upper()
    return ""


def _fetch_gate_with_retries(detail_id: str) -> str:
    for attempt in range(DME_DETAIL_ATTEMPTS):
        gate = _fetch_gate(detail_id)
        if gate or attempt == DME_DETAIL_ATTEMPTS - 1:
            return gate
        time_lib.sleep(DME_DETAIL_RETRY_PAUSE_SECONDS)
    return ""


def _request_text(url: str, data: bytes | None = None, headers: dict[str, str] | None = None) -> str:
    request_headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
        "Accept-Language": "ru-RU,ru;q=0.9,en;q=0.8",
    }
    if headers:
        request_headers.update(headers)
    request = urllib.request.Request(url, data=data, headers=request_headers, method="POST" if data else "GET")
    last_error: Exception | None = None
    contexts = [ssl.create_default_context(), ssl._create_unverified_context()]
    for context in contexts:
        try:
            with urllib.request.urlopen(request, timeout=30, context=context) as response:
                charset = response.headers.get_content_charset() or "utf-8"
                return response.read().decode(charset, errors="replace")
        except (urllib.error.URLError, TimeoutError, ssl.SSLError, OSError) as exc:
            last_error = exc
    raise RuntimeError(f"Cannot fetch DME official board: {last_error}")


def _flight_keys(flight: dict[str, Any]) -> set[str]:
    airline = flight.get("airline") or {}
    code = _normalize_code(f"{airline.get('iata', '')} {flight.get('flightNumber', '')}")
    if not code:
        return set()
    times = {
        _time_text((flight.get("originalTime") or {}).get("text")),
        _time_text((flight.get("newTime") or {}).get("text")),
    }
    return {f"{code}|{value}" for value in times if value}


def _normalize_code(value: str) -> str:
    return re.sub(r"[^A-Za-zА-Яа-я0-9]", "", value or "").upper()


def _split_flight_code(value: str) -> tuple[str, str]:
    code = _normalize_code(value)
    if len(code) >= 3 and code[:2].isalnum() and any(char.isalpha() for char in code[:2]) and code[2].isdigit():
        return code[:2], code[2:]
    if len(code) >= 4 and code[:3].isalpha() and code[3].isdigit():
        return code[:3], code[3:]
    return "", ""


def _known_gate(flight: dict[str, Any]) -> bool:
    departure = flight.get("departure") or {}
    gate = str(departure.get("gate") or "").strip()
    return bool(gate and gate.lower() not in {"не указан", "not available", "n/a", "--", "$undefined"})


def _is_near_now(value: str, now: datetime) -> bool:
    parsed = _parse_hhmm(value)
    if not parsed:
        return False
    flight_dt = datetime.combine(now.date(), parsed, tzinfo=now.tzinfo)
    return now - DME_GATE_LOOKBACK <= flight_dt <= now + DME_GATE_LOOKAHEAD


def _parse_hhmm(value: str) -> time | None:
    match = re.match(r"^(\d{1,2}):(\d{2})$", value or "")
    if not match:
        return None
    hour = int(match.group(1))
    minute = int(match.group(2))
    if hour > 23 or minute > 59:
        return None
    return time(hour, minute)


def _time_text(value: str) -> str:
    match = re.search(r"\d{1,2}:\d{2}", value or "")
    return match.group(0) if match else ""


def _plain(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", value or ""))).replace("\xa0", " ").strip()
