from __future__ import annotations

import html
import json
import re
import ssl
import time as time_lib
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from typing import Any
from zoneinfo import ZoneInfo

from .airport_gate_enrichment import GateRow
from .settings import MOSCOW_TZ


def apply() -> None:
    """Install narrow runtime fixes without touching stable reporting code."""
    from . import airport_gate_enrichment as enrichment

    enrichment.fetch_vko_official_gate_rows_for_date = fetch_vko_official_gate_rows_for_date
    enrichment.enrich_dme_gates = enrich_dme_gates


VKO_URL = "https://www.vnukovo.ru/ru/for-passengers/reysi/online-tablo/"
DME_LIST_URL = "https://m.dme.ru/Ru/autogenerated/Flight/OnlineTableFlightList"
DME_DETAIL_URL = "https://m.dme.ru/Ru/autogenerated/Flight/DetailedFlight"
DME_REFERER = "https://m.dme.ru/passengers/flight/live-board/?column=4&sort=1&direction=D&page=1"
DME_GATE_LOOKBACK = timedelta(minutes=90)
DME_GATE_LOOKAHEAD = timedelta(minutes=150)
DME_MAX_DETAIL_CHECKS = 35


def fetch_vko_official_gate_rows_for_date(target_date: date) -> tuple[list[GateRow], list[str]]:
    rows: list[GateRow] = []
    errors: list[str] = []
    seen: set[tuple[str, str, str, str]] = set()
    date_param = _vko_date_param(target_date)

    for hour in range(24):
        url = f"{VKO_URL}?bound=departure&date={date_param}&from={hour}"
        try:
            text = _request_text(url)
        except Exception as exc:
            errors.append(f"{url}: {exc}")
            continue

        parsed = _parse_vko_rows(text)
        if not parsed:
            errors.append(f"{url}: no parseable rows")
            continue
        for row in parsed:
            key = (row.flight_code, row.scheduled_time, row.destination_iata, row.gate)
            if key in seen:
                continue
            seen.add(key)
            rows.append(row)

    return rows, errors


def _vko_date_param(target_date: date) -> str:
    today = datetime.now(ZoneInfo(MOSCOW_TZ)).date()
    if target_date == today:
        return "today"
    if target_date == today - timedelta(days=1):
        return "yesterday"
    if target_date == today - timedelta(days=2):
        return "beforeyesterday"
    return target_date.isoformat()


def _parse_vko_rows(text: str) -> list[GateRow]:
    rows = _parse_vko_json_rows(text)
    rows.extend(_parse_vko_text_rows(text))
    deduped: list[GateRow] = []
    seen: set[tuple[str, str, str, str]] = set()
    for row in rows:
        key = (row.flight_code, row.scheduled_time, row.destination_iata, row.gate)
        if not row.flight_code or not row.gate or key in seen:
            continue
        seen.add(key)
        deduped.append(row)
    return deduped


def _parse_vko_json_rows(text: str) -> list[GateRow]:
    rows: list[GateRow] = []
    for payload in _json_payloads(text):
        for record in _iter_dicts(payload):
            rows.extend(_gate_rows_from_vko_record(record))
    return rows


def _json_payloads(text: str) -> list[Any]:
    payloads: list[Any] = []
    for block in re.findall(r"<script[^>]*>(.*?)</script>", text, re.S | re.I):
        block = html.unescape(block).strip()
        for candidate in _json_candidates(block):
            try:
                payloads.append(json.loads(candidate))
            except json.JSONDecodeError:
                continue
    return payloads


def _json_candidates(text: str) -> list[str]:
    values: list[str] = []
    stripped = text.strip()
    if stripped.startswith("{") or stripped.startswith("["):
        values.append(stripped)
    for match in re.finditer(r"self\.__next_f\.push\(\s*(\[.*?\])\s*\)", text, re.S):
        values.append(match.group(1))
    for marker in ("__NEXT_DATA__", "initialState", "pageProps"):
        index = text.find(marker)
        if index < 0:
            continue
        start = min([pos for pos in (text.find("{", index), text.find("[", index)) if pos >= 0], default=-1)
        if start >= 0:
            fragment = _balanced_json(text, start)
            if fragment:
                values.append(fragment)
    return values


def _balanced_json(text: str, start: int) -> str:
    opening = text[start]
    closing = "}" if opening == "{" else "]"
    depth = 0
    in_string = False
    escape = False
    for pos in range(start, len(text)):
        char = text[pos]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == opening:
            depth += 1
        elif char == closing:
            depth -= 1
            if depth == 0:
                return text[start:pos + 1]
    return ""


def _iter_dicts(value: Any):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from _iter_dicts(child)
    elif isinstance(value, list):
        for child in value:
            yield from _iter_dicts(child)


def _gate_rows_from_vko_record(record: dict[str, Any]) -> list[GateRow]:
    flight_codes = _json_values_near(record, ("flight", "number", "рейс", "code", "iata"), max_depth=2)
    flight_codes = [_normalize_flight_code(value) for value in flight_codes]
    flight_codes = [value for value in flight_codes if _looks_like_flight_code(value)]
    if not flight_codes:
        return []

    gate = _clean_gate(_first(_json_values_near(record, ("gate", "exit", "выход"), max_depth=2)))
    terminal = _clean_terminal(_first(_json_values_near(record, ("terminal", "терм"), max_depth=2)))
    scheduled_time = _first_time(_json_values_near(record, ("time", "scheduled", "план"), max_depth=2))
    actual_time = _first_time(_json_values_near(record, ("actual", "fact", "status", "статус", "вылетел", "посадку"), max_depth=2))
    destination = _first_destination(_json_leaf_strings(record))
    destination_iata = _extract_iata(destination)
    destination_name = _clean_destination(destination)

    if not gate or not scheduled_time:
        return []

    return [
        GateRow(
            flight_code=code,
            scheduled_time=scheduled_time,
            actual_time=actual_time,
            terminal=terminal,
            gate=gate,
            destination_iata=destination_iata,
            destination_name=destination_name,
            source_label="official VKO archive",
        )
        for code in _unique(flight_codes)
    ]


def _json_values_near(value: Any, needles: tuple[str, ...], max_depth: int, depth: int = 0) -> list[str]:
    result: list[str] = []
    if depth > max_depth:
        return result
    if isinstance(value, dict):
        for key, child in value.items():
            key_text = str(key).lower()
            if any(needle in key_text for needle in needles):
                result.extend(str(item) for item in _json_leaf_strings(child))
            elif not isinstance(child, list):
                result.extend(_json_values_near(child, needles, max_depth, depth + 1))
    return result


def _json_leaf_strings(value: Any) -> list[str]:
    if isinstance(value, dict):
        result: list[str] = []
        for child in value.values():
            result.extend(_json_leaf_strings(child))
        return result
    if isinstance(value, list):
        result: list[str] = []
        for child in value:
            result.extend(_json_leaf_strings(child))
        return result
    if value is None:
        return []
    return [str(value)]


def _parse_vko_text_rows(text: str) -> list[GateRow]:
    plain = _html_to_lines(text)
    rows: list[GateRow] = []
    for index, line in enumerate(plain):
        if not re.fullmatch(r"\d{1,2}:\d{2}", line):
            continue
        block = plain[index:index + 28]
        terminal_index = _first_terminal_index(block)
        search_block = block[:terminal_index] if terminal_index is not None else block
        flight_codes = _unique(
            _normalize_flight_code(value)
            for value in re.findall(
                r"\b(?:[A-ZА-Я]\d|[A-ZА-Я]{2,3}|\d[A-ZА-Я])\s*\d{1,4}[A-ZА-Я]?\b",
                " ".join(search_block),
                re.I,
            )
        )
        flight_codes = [value for value in flight_codes if _looks_like_flight_code(value)]
        if not flight_codes:
            continue
        terminal, gate = _terminal_gate_from_lines(block)
        if not gate:
            continue
        destination = _destination_from_lines(block)
        destination_iata = _extract_iata(" ".join(block)) or _extract_iata(destination)
        actual = _actual_time_from_lines(block)
        for code in flight_codes:
            rows.append(
                GateRow(
                    flight_code=code,
                    scheduled_time=line,
                    actual_time=actual,
                    terminal=terminal,
                    gate=gate,
                    destination_iata=destination_iata,
                    destination_name=destination,
                    source_label="official VKO archive",
                )
            )
    return rows


def _html_to_lines(text: str) -> list[str]:
    text = re.sub(r"</(?:div|span|p|li|tr|td|th|section|article|h\d)>", "\n", text, flags=re.I)
    text = re.sub(r"<br\s*/?>", "\n", text, flags=re.I)
    text = html.unescape(re.sub(r"<[^>]+>", " ", text))
    return [line.strip() for line in re.split(r"[\r\n]+", text) if line.strip()]


def _terminal_gate_from_lines(lines: list[str]) -> tuple[str, str]:
    for index, line in enumerate(lines):
        terminal = _clean_terminal(line)
        if not terminal:
            continue
        for candidate in lines[index + 1:index + 5]:
            gate = _clean_gate(candidate)
            if gate:
                return terminal, gate
    return "", ""


def _first_terminal_index(lines: list[str]) -> int | None:
    for index, line in enumerate(lines):
        if _clean_terminal(line):
            return index
    return None


def _destination_from_lines(lines: list[str]) -> str:
    for line in lines[1:8]:
        if re.fullmatch(r"[A-ZА-Я0-9]{2,4}", line):
            continue
        if _looks_like_flight_code(_normalize_flight_code(line)):
            continue
        if re.search(r"[А-Яа-яA-Za-z]", line):
            return _clean_destination(line)
    return ""


def _actual_time_from_lines(lines: list[str]) -> str:
    for line in lines:
        match = re.search(r"(?:вылетел|вылет|departed)\D{0,12}(\d{1,2}:\d{2})", line, re.I)
        if match:
            return match.group(1)
    return ""


def _first_destination(values: list[str]) -> str:
    for value in values:
        value = str(value or "").strip()
        if not value or len(value) <= 2:
            continue
        if re.fullmatch(r"\d{1,3}[A-ZА-Я]?", value, re.I):
            continue
        if re.fullmatch(r"[A-ZА-Я]", value, re.I):
            continue
        if re.fullmatch(r"\d{1,2}:\d{2}", value):
            continue
        if re.search(r"[А-Яа-яA-Za-z]", value) and not _looks_like_flight_code(_normalize_flight_code(value)):
            if not any(word in value.lower() for word in ("совершил", "вылетел", "посадку", "отмен", "terminal", "gate")):
                return value
    return ""


@dataclass(frozen=True)
class DmeRow:
    flight_code: str
    planned_time: str
    detail_id: str


def enrich_dme_gates(flights: list[dict[str, Any]]) -> dict[str, Any]:
    now = datetime.now(ZoneInfo(MOSCOW_TZ))
    missing_flights = [flight for flight in flights if not _known_gate(flight)]
    if not missing_flights:
        return {"dme_missing_before": 0, "dme_official_checked": 0, "dme_official_filled": 0}

    try:
        rows = _fetch_dme_rows(now)
    except Exception as exc:
        return {"dme_missing_before": len(missing_flights), "dme_official_checked": 0, "dme_official_error": str(exc)}

    checked = 0
    gates: dict[str, str] = {}
    errors: list[str] = []
    for row in rows:
        key = f"{_normalize_flight_code(row.flight_code)}|{row.planned_time}"
        if not _is_near_now(row.planned_time, now):
            continue
        if checked >= DME_MAX_DETAIL_CHECKS:
            break
        checked += 1
        try:
            gate = _fetch_dme_gate(row.detail_id)
        except Exception as exc:
            errors.append(f"{row.flight_code} {row.planned_time}: {exc}")
            continue
        if gate:
            gates[key] = gate
        time_lib.sleep(0.2)

    existing_keys = {key for flight in flights for key in _flight_keys(flight)}
    filled = 0
    for flight in flights:
        gate = next((gates[key] for key in _flight_keys(flight) if key in gates), "")
        if not gate:
            continue
        departure = flight.setdefault("departure", {})
        departure["gate"] = gate
        departure["terminal"] = departure.get("terminal") or "T1"
        departure["gateSource"] = "official DME live board"
        departure["gateMatch"] = "official DME: flight + scheduled/new time"
        flight["secondaryCorner"] = f"Gate {gate}"
        filled += 1

    added = 0
    for row in rows:
        key = f"{_normalize_flight_code(row.flight_code)}|{row.planned_time}"
        gate = gates.get(key)
        if not gate or key in existing_keys:
            continue
        airline, number = _split_flight_code(row.flight_code)
        if not airline or not number:
            continue
        flights.append(
            {
                "id": f"DME-official-{_normalize_flight_code(row.flight_code)}-{row.planned_time}",
                "airline": {"iata": airline, "name": ""},
                "flightNumber": number,
                "city": "",
                "arrival": {"iata": "", "flag": "", "countryCode": ""},
                "departure": {"iata": "DME", "terminal": "T1", "gate": gate, "gateSource": "official DME live board", "gateMatch": "official DME: flight + time"},
                "dataQuality": "gate from official DME live board; destination filled from post-fact source",
                "originalTime": {"text": row.planned_time},
                "newTime": {"text": ""},
                "secondaryCorner": f"Gate {gate}",
                "status": [{"type": "text", "text": "Scheduled"}],
            }
        )
        existing_keys.add(key)
        added += 1

    return {
        "dme_missing_before": len(missing_flights),
        "dme_missing_after": max(len(missing_flights) - filled, 0),
        "dme_official_rows": len(rows),
        "dme_official_checked": checked,
        "dme_official_filled": filled,
        "dme_official_added_gate_candidates": added,
        "dme_official_detail_errors": errors[:3],
    }


def _fetch_dme_rows(now: datetime) -> list[DmeRow]:
    result: list[DmeRow] = []
    seen: set[str] = set()
    for page in range(4):
        body = urllib.parse.urlencode({"CurrDateStr": now.date().isoformat(), "SearchText": "", "direction": "D", "PeriodDay": "0", "Page": str(page)}).encode()
        text = _request_text(DME_LIST_URL, data=body, headers={"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8", "X-Requested-With": "XMLHttpRequest", "Referer": DME_REFERER})
        rows = [row for row in _parse_dme_rows(text) if row.detail_id not in seen]
        if not rows:
            break
        for row in rows:
            seen.add(row.detail_id)
        result.extend(rows)
    return result


def _parse_dme_rows(text: str) -> list[DmeRow]:
    rows: list[DmeRow] = []
    for block in re.findall(r"<li\b.*?</li>", text, re.S | re.I):
        detail = re.search(r"DetailedFlight\?id=(\d+)", block)
        planned = re.search(r"plannedDateFlight[^>]*>\s*([^<]+)", block, re.S | re.I)
        flight = re.search(r"flightNumber.*?<div[^>]*>\s*(.*?)\s*</div>", block, re.S | re.I)
        if not detail or not planned or not flight:
            continue
        code_match = re.search(r"\b([A-ZА-Я0-9]{1,3})\s*0*([0-9]{1,4}[A-ZА-Я]?)\b", _plain(flight.group(1)), re.I)
        time_text = _first_time([_plain(planned.group(1))])
        if code_match and time_text:
            rows.append(DmeRow(f"{code_match.group(1)} {code_match.group(2)}", time_text, detail.group(1)))
    return rows


def _fetch_dme_gate(detail_id: str) -> str:
    text = _request_text(f"{DME_DETAIL_URL}?id={urllib.parse.quote(detail_id)}", headers={"Referer": DME_REFERER})
    plain = _plain(text)
    for pattern in (r"\b(?:Гейт|Gate)\s*[:№]?\s*([A-ZА-Я]?\d+[A-ZА-Я]?)\b", r"\b(?:Выход на посадку|Boarding gate)\s*[:№]?\s*([A-ZА-Я]?\d+[A-ZА-Я]?)\b"):
        match = re.search(pattern, plain, re.I)
        if match:
            return _clean_gate(match.group(1))
    return ""


def _request_text(url: str, data: bytes | None = None, headers: dict[str, str] | None = None) -> str:
    request_headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
        "Accept-Language": "ru-RU,ru;q=0.9,en;q=0.8",
    }
    if headers:
        request_headers.update(headers)
    request = urllib.request.Request(url, data=data, headers=request_headers, method="POST" if data else "GET")
    with urllib.request.urlopen(request, timeout=45, context=ssl.create_default_context()) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def _flight_keys(flight: dict[str, Any]) -> set[str]:
    airline = flight.get("airline") or {}
    code = _normalize_flight_code(f"{airline.get('iata', '')} {flight.get('flightNumber', '')}")
    times = {_first_time([(flight.get("originalTime") or {}).get("text")]), _first_time([(flight.get("newTime") or {}).get("text")])}
    return {f"{code}|{value}" for value in times if code and value}


def _is_near_now(value: str, now: datetime) -> bool:
    parsed = _parse_hhmm(value)
    if not parsed:
        return False
    flight_dt = datetime.combine(now.date(), parsed, tzinfo=now.tzinfo)
    return now - DME_GATE_LOOKBACK <= flight_dt <= now + DME_GATE_LOOKAHEAD


def _parse_hhmm(value: str) -> time | None:
    match = re.fullmatch(r"(\d{1,2}):(\d{2})", value or "")
    if not match:
        return None
    hour, minute = int(match.group(1)), int(match.group(2))
    if hour > 23 or minute > 59:
        return None
    return time(hour, minute)


def _known_gate(flight: dict[str, Any]) -> bool:
    gate = str((flight.get("departure") or {}).get("gate") or "").strip().lower()
    return bool(gate and gate not in {"не указан", "not available", "n/a", "--", "$undefined", "none", "null"})


def _clean_gate(value: Any) -> str:
    text = str(value or "").upper().replace(" ", "")
    match = re.search(r"\d{1,3}", text)
    return match.group(0) if match else ""


def _clean_terminal(value: Any) -> str:
    text = str(value or "").upper().strip()
    match = re.search(r"\b([A-ZА-Я])\b", text)
    return match.group(1) if match else ""


def _normalize_flight_code(value: Any) -> str:
    return re.sub(r"[^A-Za-zА-Яа-я0-9]", "", str(value or "")).upper().translate(str.maketrans({"А": "A", "В": "B", "Е": "E", "К": "K", "М": "M", "Н": "H", "О": "O", "Р": "P", "С": "C", "Т": "T", "Х": "X"}))


def _split_flight_code(value: str) -> tuple[str, str]:
    code = _normalize_flight_code(value)
    if len(code) >= 3 and any(char.isalpha() for char in code[:2]) and code[2].isdigit():
        return code[:2], code[2:]
    if len(code) >= 4 and code[:3].isalpha() and code[3].isdigit():
        return code[:3], code[3:]
    return "", ""


def _looks_like_flight_code(value: str) -> bool:
    value = str(value or "").upper()
    if not re.search(r"[A-ZА-Я]", value):
        return False
    if re.fullmatch(r"[A-ZА-Я]\d{1,3}[A-ZА-Я]?", value):
        return False
    return bool(re.fullmatch(r"(?:[A-ZА-Я]\d|[A-ZА-Я]{2,3}|\d[A-ZА-Я])\d{1,4}[A-ZА-Я]?", value))


def _first_time(values: list[str]) -> str:
    for value in values:
        match = re.search(r"\d{1,2}:\d{2}", str(value or ""))
        if match:
            return match.group(0)
    return ""


def _extract_iata(value: str) -> str:
    matches = re.findall(r"\b[A-Z]{3}\b", str(value or ""))
    for match in matches:
        if match not in {"VKO", "DME", "SVO"}:
            return match
    return ""


def _clean_destination(value: str) -> str:
    text = re.sub(r"\b[A-Z]{3}\b", "", str(value or ""))
    text = re.sub(r"\s+", " ", text).strip(" -|,")
    return text


def _first(values: list[str]) -> str:
    return str(values[0]) if values else ""


def _unique(values) -> list[str]:
    result: list[str] = []
    for value in values:
        value = str(value or "").strip()
        if value and value not in result:
            result.append(value)
    return result


def _plain(value: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", value or ""))).replace("\xa0", " ").strip()
